
LittlerootTown_BrendansHouse_1F_MapScripts::
	.byte 0

LittlerootTown_BrendansHouse_1F_EventScript_BrendansMom::
	msgbox LittlerootTown_BrendansHouse_1F_Text_BrendansMom, MSGBOX_NPC
	end

LittlerootTown_BrendansHouse_1F_Text_BrendansMom:
	.string "Oh! Hello, {PLAYER}. If you're\n"
	.string "looking for the professor, you'll\l"
	.string "find him in his lab.\p"
	.string "Brendan should be with him as well,\n"
	.string "assuming those two aren't out doing\l"
	.string "research in the field.$"
	